### ISSUE TITLE
Create mainpage

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#11]
**Value Proposition**
As a user, I need clickable category buttons to be able to navigate to the category I am looking for.

**Description**
<img width="306" alt="Bildschirmfoto 2022-10-11 um 10 51 39" src="https://user-images.githubusercontent.com/94837451/195044911-04f6413b-88dc-4ecb-b36e-25f342a9bccd.png">

**Acceptance Criteria**
- [x] Add a placeholder image as a space for later at the top
- [x] Icon buttons like in the scribble
- [x] Clickable icon buttons to navigate to the category page

**Tasks**
- [x] Add the `placeholderimg` component to the top at the main page
- [x] Fetch data from database to get to the `button icon`
- [x] Add `link` to the fetched button icons to the category behind it
- [x] Use `dynamic routing` through the database

**Comment by DanielGennat** [comment]
Hi Felix,
some suggestions:
- use bold text for your headlines e.g. `**Value Proposition**`

**Acceptance Criteria**
- a placeholder image at the top
-  Clickable icon buttons to navigate to the category page

**Tasks**
- create a `HeaderImage` component
- create `links` for the categories
- fetch data from database to get the button icons
- style the links as buttons and add the icons
- use ...

**Comment by ostermann-felix** [comment]
Updated
