### ISSUE TITLE
create category page

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#12]
**Value Proposition**
As a user, I have to find the links to the lessons at the category page to know what I want to look for.

**Description**
<img width="302" alt="Bildschirmfoto 2022-10-11 um 11 01 12" src="https://user-images.githubusercontent.com/94837451/195046814-a7629103-4db4-419c-9483-496daf1aa2a8.png">

**Acceptance Criteria**

- [x] category icon to the category page 
- [x] category headline next to the category icon at the category page
- [x] clickable link to the lesson at the corresponding page
- [x] the icons and headline and link informations has to be from the database

**Tasks**

- [x] add the fetch for the icon and headline
- [x] add the link to the lesson underneath

**Comment by DanielGennat** [comment]
Hey Felix,
- just describe the acceptance criteria without instructions like 'add' or 'create'. This is a good example: ' clickable link to the lesson at the corresponding page'
- they _have_ to be :)

**Comment by ostermann-felix** [comment]
Updated
