### ISSUE TITLE
creating first content page

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#2]
**Value Proposition**
As a volunteer doing first aid, I want to get step by step instructions for the necessary emergency measure that has to be done.

**Description**
![content page ](https://user-images.githubusercontent.com/94837451/190421038-9337a6a6-0c12-4665-9564-0c39ccc2ab89.png)

**Acceptance Criteria**
content:
- [x] a full size mobile content field with text content and embeddet picture dummys 
- [x] a scrollable content box if content is more than the standard size mobile screen can display

**Tasks**

- [x] create a new react app and add a git repository to it
- [x] add a component to the page with the content box in it
- [x] create the content and add it into the content box
- [ ] add picture dummys to the text to break up the text flow
- [x] use style components to style the box

**Comment by DoroVernier** [comment]
Wow! da hast du ja schon viel Arbeit reingesteckt. 
Vielleicht solltest du dir nochmal überlegen, welche EINE Funktionalität du als erstes coden willst und brichst diese erste User-Story darauf runter. Den Rest dieser vielen Arbeit kannst du dann ja nach und nach in die nächste US einführen.

**Comment by MerleMak** [comment]
Nice job! 
The only thing which i have to remark: It would be great if you could keep the sentence structure as discussed: 
As a volunteer,
I need ...
to be able to ...
Also you could add an Acceptance Criteria, that the content box is scrollable (as you wireframe suggests)

Other than that, you are good to go :)
