### ISSUE TITLE
creating a second page with different content

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#3]
**Value Proposition**
As a volunteer I need a second page to be able to learn more medical topics.

**Description**
![userstory1](https://user-images.githubusercontent.com/94837451/190663905-84d8003c-db43-409c-b27d-9312f6b386d4.png)

**Acceptance Criteria**
content:
- [x] a full size mobile content field with text content and embeddet picture dummys 
- [x] a scrollable content box if content is more than the standard size mobile screen can display

**Tasks**

- [x] create a second page
- [x] add a component to the page with the content box in it
- [x] create the content and add it into the content box
- [ ] add picture dummys to the text to break up the text flow
- [x] use style components to style the box

**Comment by NikRoe** [comment]
Hey Felix, 
nice work so far. A few suggestions you might want to include in your user story:
- It would be great if you could keep the sentence structure as discussed:
As a volunteer,
I need ...
to be able to ...
- though the design will be as in your previous user story, it would be great to have some sort of scribble/wireframe to get an impression of how it will look in the end :)
