### ISSUE TITLE
create fixed footer add navigation arrows

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#4]
**Value Proposition**
As a volunteer, I need to find usable buttons to be able to click trough the content in the footer.

**Description**
![userstory2](https://user-images.githubusercontent.com/94837451/190649170-adf6707c-e7e8-46d5-a936-eefbbfc649a8.png)

**Acceptance Criteria**
content:
- [x] a fixed footer in the same style like the main content pages
- [ ] buttons in arrow design
- [ ] clickable arrow buttons what brings the user to the next content page

**Tasks**

- [x] create a footer as a component
- [x] set the footer fixed to bottom of the page
- [ ] add buttons and style as an arrow
- [ ] make the buttons clickable that they lead to the next content

**Comment by MerleMak** [comment]
Hi Felix, 
Please remember to use the given structure with 
As a ... (here user would be fitting already, as you already stated in the first user story who your target audience is)
I need ...
to be able to ... (!!)

Other than that, it looks good to me :)
