### ISSUE TITLE
create header and title 

### ISSUE THREAD

**Issue by ostermann-felix** [ostermann-felix/capstone-project#5]
**Value Proposition**
As a volunteer, I need to find the title of the app at the top of my screen inside an header.

**Description**
![userstory4](https://user-images.githubusercontent.com/94837451/190687539-fa0bd45a-6a9a-46d1-a10e-b5a014e00803.png)

**Acceptance Criteria**
content:
- [x] a fixed header in the same style like the main content pages
- [x] a app title flush right

**Tasks**
- [x] create a header as a component
- [x] set the footer fixed to top of the page
- [x] add the app title flush right

**Comment by AnH13-6** [comment]
Hi! I think you meant "header" instead of "footer" in the second task, right? 
You could also add a mock title like "title" in your wireframe, so that one can easily see where you want to put it. 
Other than that, good job! :)
